import {useEffect,useRef,useState,type RefObject} from 'react';
import {useNavigate} from 'react-router-dom';
import {STOPS} from '../data';
import {TrainSound} from '../animation/TrainSound';
import {sceneControls} from './scene-adapter';
import './journey-flow.css';
const KEY='shosholoza:connected-trip:v1';
type Trip={town:string;legs:string[];positions:Record<string,string>;elapsed:number;sound:boolean;complete:boolean};
function read():Trip{try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v&&STOPS.some(s=>s.id===v.town))return {town:v.town,legs:Array.isArray(v.legs)?v.legs:[],positions:v.positions||{},elapsed:Number.isFinite(v.elapsed)?Math.max(0,Math.min(12,v.elapsed)):0,sound:v.sound===true,complete:v.complete===true};}catch{}return{town:'pretoria',legs:[],positions:{},elapsed:0,sound:false,complete:false};}
function write(v:Trip){try{localStorage.setItem(KEY,JSON.stringify(v));}catch{}}
const landmarks=[/Visit station|Explore Union|Freedom Park/,/City reveal|Street level/,/^Big Hole$/,/Inspect candidate 1/,/^Explore$/, /Explore landmark/,/Explore landmark/,/Begin the finale|Continue to the harbour/];
export function JourneyFlow({town,frame,ready,onGuide}:{town:string;frame:RefObject<HTMLIFrameElement|null>;ready:boolean;onGuide:()=>void}){
 const nav=useNavigate(),index=STOPS.findIndex(s=>s.id===town),next=STOPS[index+1];
 const [saved]=useState(read),trip=useRef<Trip>({...saved,town,elapsed:saved.town===town?saved.elapsed:0});
 const [seconds,setSeconds]=useState(trip.current.elapsed),[travelling,setTravelling]=useState(trip.current.elapsed>0),[paused,setPaused]=useState(true),[sound,setSound]=useState(saved.sound),[message,setMessage]=useState(''),[finished,setFinished]=useState(saved.complete&&town==='cape-town');
 const progress=useRef(trip.current.elapsed),audio=useRef<TrainSound|null>(null),restored=useRef(false),lastSaved=useRef('');
 const controls=()=>{const doc=frame.current?.contentDocument;return doc?.querySelector('canvas')?sceneControls(doc,town):null;};
 const pauseScene=()=>{const c=controls();if(!c)return;const run=c.run?.textContent||'',p=c.pause?.textContent||'';if(/Pause/.test(run)&&c.run)c.run.click();else if(/running/i.test(run)&&/^Pause/.test(p))c.pause?.click();if(c.sound&&/\bon\b/i.test(c.sound.textContent||''))c.sound.click();};
 useEffect(()=>{audio.current=new TrainSound();return()=>{audio.current?.dispose();};},[]);
 useEffect(()=>{if(!ready||restored.current)return;restored.current=true;const c=controls(),position=trip.current.positions[town];if(c?.range&&position!==undefined){c.change(c.range,position);setMessage('Saved position restored, paused.');}else if(saved.town===town&&position)setMessage('This scene resumes at its chapter start.');pauseScene();},[ready]);
 useEffect(()=>{const timer=setInterval(()=>{if(travelling)return;const c=controls();if(c?.range){const value=c.range.value;if(value!==lastSaved.current){trip.current.positions[town]=value;lastSaved.current=value;write(trip.current);}}},1000);return()=>clearInterval(timer);},[travelling,town]);
 useEffect(()=>{if(!travelling)return;let id=0,last=performance.now(),checkpoint=0;
 const tick=(now:number)=>{const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!document.hidden){progress.current=Math.min(12,progress.current+dt);setSeconds(progress.current);trip.current.elapsed=progress.current;}
 const t=progress.current,speed=t<3?18*(t/3)**2:t>9?18*((12-t)/3)**2:18;
 audio.current?.update({speed,dt,distance:t*12,nearCrossing:false,paused:paused||document.hidden,atStation:speed<1,cameraMode:'FOLLOW',environment:'OPEN'});
 if(now-checkpoint>800){write(trip.current);checkpoint=now;}
 if(t>=12){const legs=[...new Set([...trip.current.legs,town])];if(next){write({...trip.current,town:next.id,legs,elapsed:0});nav('/experience/'+next.id);}else{trip.current={...trip.current,legs,elapsed:0,complete:true};write(trip.current);setFinished(true);setTravelling(false);setPaused(true);audio.current?.disable();}return;}id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[travelling,paused,next?.id]);
 const depart=async()=>{pauseScene();setMessage('');setTravelling(true);setPaused(false);if(sound)try{await audio.current?.enable();}catch{setSound(false);trip.current.sound=false;setMessage('Audio unavailable; travel continues.');}};
 const toggleSound=async()=>{const value=!sound;setSound(value);trip.current.sound=value;write(trip.current);try{if(travelling){if(value)await audio.current?.enable();else audio.current?.disable();}else{const c=controls();if(c?.sound&&/\bon\b/i.test(c.sound.textContent||'')!==value)c.sound.click();}}catch{setMessage('Audio unavailable.');}};
 const landmark=()=>{const c=controls();const b=c?.landmarkVisit??c?.actions.find(b=>landmarks[index].test(b.textContent||'')&&!b.disabled);if(b){b.click();setMessage('Landmark view opened. Use a camera button to return to the train.');}else onGuide();};
 return <>
 <div className="trip-flow" aria-label="Connected journey"><button disabled={!ready||travelling||!!controls()?.landmarkVisit?.disabled} onClick={landmark}>{town==='pretoria'?'Visit Union Buildings':'Visit main landmark'}</button><button disabled={!controls()?.landmarkReturn||controls()?.landmarkReturn?.disabled} onClick={()=>controls()?.landmarkReturn?.click()}>Return to train</button>{town==='pretoria'&&<button disabled={controls()?.landmarkPause?.disabled??true} onClick={()=>controls()?.landmarkPause?.click()}>{controls()?.landmarkPause?.textContent??'Pause landmark'}</button>}<button disabled={!ready||travelling} onClick={()=>{pauseScene();delete trip.current.positions[town];trip.current.elapsed=0;write(trip.current);frame.current?.contentWindow?.location.reload();setMessage('Scene restarted.');}}>Restart town</button><button disabled={!ready||travelling} onClick={depart}>{next?'Continue journey':'Finish at Cape Town'}</button><button aria-pressed={sound} onClick={toggleSound}>{sound?'Journey sound on':'Journey sound off'}</button><span>{trip.current.legs.length}/8 travel sequences finished</span>
 {saved.town!==town&&<button onClick={()=>nav('/experience/'+saved.town)}>Resume saved trip</button>}<small role="status">{message||'Visit a landmark or continue. Skipping does not earn a chapter stamp.'}</small></div>
 {travelling&&<section className="trip-transition" role="dialog" aria-modal="true" aria-label="Travel between towns" data-region={index<2?'highveld':index<5?'karoo':index===5?'mountains':'coast'}>
 <h2>{seconds<3?`Leaving ${STOPS[index].name}`:seconds<9?`${STOPS[index].name} → ${next?.name??'Cape Town terminus'}`:`Arriving at ${next?.name??'Cape Town terminus'}`}</h2><p>Compressed travel animation · illustrative landscape</p>
 <svg viewBox="0 0 1000 340" role="img" aria-label="Animated train passing through changing countryside"><rect width="1000" height="340" fill="var(--trip-sky)"/><g transform={`translate(${-seconds*12%180},0)`}>{Array.from({length:8},(_,i)=><path key={i} d={`M${i*180-100} 245 l100 -${index>=5?150:65} l110 ${index>=5?150:65}Z`} fill="var(--trip-hill)"/>)}</g><rect y="235" width="1000" height="105" fill="var(--trip-ground)"/><path d="M0 298H1000M0 308H1000" stroke="#43484c" strokeWidth="4"/><g transform={`translate(${seconds<3?90+seconds*seconds*14:seconds>9?216+(seconds-9)*18-(seconds-9)**2*3:216},0)`}>{['#ebb937','#2fa8c6','#7e63a8','#2fa8c6','#8b76b8'].map((c,i)=><g key={i} transform={`translate(${i*90},0)`}><rect y="249" width="84" height="40" rx="5" fill={c}/><rect y="246" x="3" width="78" height="6" rx="3" fill="#bbc1c1"/>{[9,24,39,54,69].map(x=><rect key={x} x={x} y="258" width="10" height="12" fill="#163842"/>)}{[15,68].map(x=><g key={x} transform={`translate(${x},290) rotate(${seconds*150})`}><circle r="8" fill="#25313a"/><path d="M-5 0H5" stroke="#9baab1" strokeWidth="2"/></g>)}</g>)}</g><text x="25" y="40" fill="#233943" fontSize="20">{index<2?'Highveld':index<5?'Great Karoo':index===5?'Hex River mountains':'Cape coast'}</text></svg>
 <progress value={seconds} max="12" aria-label="Travel progress"/><div><button onClick={()=>setPaused(!paused)}>{paused?'Resume travel':'Pause travel'}</button><button onClick={()=>{audio.current?.disable();setTravelling(false);setPaused(true);progress.current=0;setSeconds(0);trip.current.elapsed=0;write(trip.current);}}>Return to town</button><button aria-pressed={sound} onClick={toggleSound}>{sound?'Mute':'Enable sound'}</button></div></section>}
 {finished&&!travelling&&<section className="trip-finished" role="status"><h2>Arrived in Cape Town</h2><p>{trip.current.legs.length} travel sequences finished. Detailed chapter stamps remain in your passport.</p><button onClick={()=>{write({...trip.current,town:'pretoria',legs:[],elapsed:0,complete:false});nav('/experience/pretoria');}}>Start another journey</button><button onClick={()=>setFinished(false)}>Explore Cape Town</button></section>}
 </>;
}
