import {chapterPath} from './JourneyHub';
import {Link} from 'react-router-dom'; import {ArrowRight,Play,MapPin} from 'lucide-react'; import {STOPS,TOTAL_HOURS,TOTAL_KM} from '../data'; import {SiteHeader} from './SiteHeader'; import {MobileTabBar} from './MobileTabBar';
import {useState} from 'react'; import {useSupabaseUser} from '../auth/useUser'; import {supabase} from '../auth/supabase'; import {logAuthEvent} from '../auth/activity';
function VerifyBanner(){
  const {user}=useSupabaseUser();
  const [resent,setResent]=useState(false);
  if(!user||user.email_confirmed_at)return null;
  async function resend(){
    if(!user?.email)return;
    await supabase.auth.resend({type:'signup',email:user.email});
    void logAuthEvent('verification-resent',user.email);
    setResent(true);
  }
  return <div className="verify-banner" role="status"><span>Please verify your email address to keep full access to your account.</span><button type="button" onClick={()=>void resend()} disabled={resent}>{resent?'Verification email sent':'Resend verification email'}</button></div>;
}
export function Landing(){return <div className="page landing"><SiteHeader tone="onImage"/><VerifyBanner/><section className="hero"><img src="/assets/photos/hero-train.webp" className="hero-image"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow gold">Pretoria → Cape Town · 8 stops</p><h1>The country goes past<span>at window height.</span></h1><p className="hero-copy">Shosholoza Trail turns the {TOTAL_KM.toLocaleString()} km rail journey across South Africa into something you can watch unfold — with the stories, food and people of every town appearing exactly as you reach them.</p><div className="hero-actions"><Link className="primary-btn" to="/animation"><Play/>Start Ride</Link><Link className="ghost-btn" to="/chapters">See the journey<ArrowRight/></Link></div><dl className="hero-stats">{[[TOTAL_KM+' km','Distance'],[TOTAL_HOURS+' hours','On the rails'],[STOPS.length+'','Towns & cities']].map(([v,k])=><div key={k}><dd>{v}</dd><dt>{k}</dt></div>)}</dl></div></section><section className="mobile-journey-card"><p className="eyebrow">Your journey</p><h3>Pretoria → Cape Town</h3><p>Step along mapped track in the first-person ride.</p><Link to="/animation"><MapPin/>Start Ride</Link></section><section className="landing-grid"><div className="section-lead"><p className="eyebrow gold-dark">The line</p><h2>Eight stops, one continuous journey.</h2></div><ol className="stop-strip" aria-label="The eight stops, in route order">{STOPS.map((s,i)=>{const path=chapterPath(s.id);const inner=<><b>{String(i+1).padStart(2,'0')}</b><strong>{s.name}</strong><small>{s.km} km</small></>;return <li key={s.id}>{path?<a href={path} aria-label={`${i+1}. ${s.name}, ${s.km} km: ride this chapter`}>{inner}</a>:<span aria-label={`${i+1}. ${s.name}, ${s.km} km: chapter coming soon`}>{inner}</span>}</li>})}</ol><Link className="text-link" to="/destinations">See all eight stops <ArrowRight/></Link><section className="dark-cta ai-landing-cta"><h2>Questions for the journey?</h2><p>Consult a source-locked AI guide about the places, people, heritage and landscapes along the trail.</p><Link to="/ai">Open the AI Guide</Link></section></section><footer className="footer"><b>Shosholoza Trail</b><span>A domestic tourism concept for the Geekulcha Train Tourism Hackathon 2027.</span><Link className="footer-link" to="/credits">Photograph credits &amp; licences</Link></footer><MobileTabBar/></div>}
