export type Stop={id:string;name:string;province:string;lon:number;lat:number;km:number;arrival:string;tagline:string;teaser:string;audioTitle:string;audioLength:string;story:string;culture:string;attractions:{name:string;kind:string;blurb:string}[];food:string[];image:string};
export const STOPS:Stop[]=[
{id:'pretoria',name:'Pretoria',province:'Gauteng',lon:28.1892212,lat:-25.7594894,km:0,arrival:'Day 1 · 08:50 departure',tagline:'Jacaranda city, where the line begins',teaser:'Purple streets, sandstone terraces and the first whistle of the trail.',audioTitle:'The morning the jacarandas fell',audioLength:'2 min local story',story:"Every October Pretoria turns violet. Seventy thousand jacarandas drop a purple carpet over the capital's avenues, and the city's oldest station fills with travellers heading south. Shosholoza Trail begins here.",culture:'Pretoria is Tshwane: Ndebele geometry, Afrikaans poetry, Sotho and Tswana traded across the platform.',attractions:[{name:'Union Buildings',kind:'Heritage',blurb:'Sandstone terraces and gardens above the city.'},{name:'Freedom Park',kind:'Memorial',blurb:'A hillside of remembrance with sweeping views.'},{name:'Marabastad',kind:'Neighbourhood',blurb:'Spice traders, bazaars and migrant history.'}],food:['Marabastad bunny chow','Koeksisters','Rooibos flat white'],image:'/assets/photos/pretoria.webp'},
{id:'johannesburg',name:'Johannesburg',province:'Gauteng',lon:28.0423048,lat:-26.1976708,km:69,arrival:'Day 1 · 10:20',tagline:'The city built on gold',teaser:'Mine dumps glowing gold at sunset and a skyline made of restless ambition.',audioTitle:'Egoli: a city of arrivals',audioLength:'3 min local story',story:'Johannesburg exists because someone found a reef of gold in 1886 and nobody went home. The train slips past mine dumps, Soweto and the CBD.',culture:'Kwaito, amapiano, isiZulu, Sesotho, galleries, jazz rooms and shisanyama.',attractions:[{name:'Constitution Hill',kind:'Heritage',blurb:'Old fort prison turned Constitutional Court.'},{name:'Vilakazi Street',kind:'Township tour',blurb:'A street with deep political and cultural history.'},{name:'Maboneng Precinct',kind:'Arts',blurb:'Galleries, markets and street murals.'}],food:['Shisanyama','Kota','Vetkoek and mince'],image:'/assets/photos/johannesburg.webp'},
{id:'kimberley',name:'Kimberley',province:'Northern Cape',lon:24.7698702,lat:-28.7353474,km:552,arrival:'Day 1 · 17:05',tagline:'The city shaped by diamonds',teaser:'A hand-dug crater 215 m deep, and the boom town that grew around its rim.',audioTitle:'Forty thousand men and a hill',audioLength:'2 min local story',story:'In 1871 a hill stood here. Within forty years, thousands of diggers had removed it with picks, buckets and rope, leaving the Big Hole and a city shaped by diamonds.',culture:'Setswana and Afrikaans conversation, mining history, San rock art and local storytelling.',attractions:[{name:'The Big Hole',kind:'Landmark',blurb:'A vast hand-excavated mine and iconic Kimberley landmark.'},{name:'McGregor Museum',kind:'Museum',blurb:'Natural and cultural history.'},{name:'Wildebeest Kuil Rock Art Centre',kind:'San heritage',blurb:'Community-run rock engraving site.'},{name:'Kimberley Ghost Trail',kind:'Evening tour',blurb:'Stories through the old mining quarter.'}],food:['Northern Cape lamb potjie','Vetkoek','Local market fare'],image:'/assets/photos/kimberley.webp'},
{id:'de-aar',name:'De Aar',province:'Northern Cape',lon:24.0138567,lat:-30.6503939,km:788,arrival:'Day 1 · 21:40',tagline:'The great junction of the Karoo',teaser:'Where every line seems to cross, under an unreasonable amount of sky.',audioTitle:'Night shift at the junction',audioLength:'2 min local story',story:'De Aar grew around one of South Africa’s major railway junctions. At night, the Karoo opens into silence and extraordinary skies.',culture:'Railway families, Afrikaans and Nama influences, and a strong stargazing identity.',attractions:[{name:'De Aar Rail Yard',kind:'Rail heritage',blurb:'A vast marshalling yard.'},{name:'Karoo night sky',kind:'Stargazing',blurb:'Exceptionally dark skies.'},{name:'Olive Schreiner House',kind:'Literary',blurb:'A local literary heritage stop.'}],food:['Karoo lamb','Moerkoffie and beskuit'],image:'/assets/photos/de-aar.webp'},
{id:'beaufort-west',name:'Beaufort West',province:'Western Cape',lon:22.5769196,lat:-32.3518393,km:1047,arrival:'Day 2 · 02:15',tagline:'Capital of the Great Karoo',teaser:'Flat-topped koppies, springbok at first light and the Great Karoo.',audioTitle:"The heart surgeon's home town",audioLength:'3 min local story',story:'Beaufort West sits in the heart of the Great Karoo beneath dramatic koppies and wide skies.',culture:'Sheep farming, Karoo hospitality and long-table dinners.',attractions:[{name:'Karoo National Park',kind:'Wildlife',blurb:'Mountain zebra, springbok and Karoo landscapes.'},{name:'Chris Barnard Museum',kind:'Museum',blurb:'Local history of the pioneering surgeon.'}],food:['Karoo lamb pie','Roosterkoek'],image:'/assets/photos/beaufort-west.webp'},
{id:'matjiesfontein',name:'Matjiesfontein',province:'Western Cape',lon:20.5808832,lat:-33.2314538,km:1277,arrival:'Day 2 · 06:30',tagline:'A Victorian village frozen in 1899',teaser:'One street, one red London bus, one hotel — and a national monument in its entirety.',audioTitle:"Jimmy Logan's refreshment room",audioLength:'2 min local story',story:'A Scottish railwayman built a Victorian spa village around a single Karoo station. The Shosholoza Trail pauses here at first light.',culture:'Karoo-Victorian eccentricity, ghost stories and railway heritage.',attractions:[{name:'Lord Milner Hotel',kind:'Heritage hotel',blurb:'A turreted Victorian hotel.'},{name:'The red London bus',kind:'Curiosity',blurb:'The village’s famous short tour.'},{name:'Marie Rawdon Museum',kind:'Museum',blurb:'Victoriana above the old station.'}],food:['Platform coffee and rusks','Karoo lamb curry'],image:'/assets/photos/matjiesfontein.webp'},
{id:'worcester',name:'Worcester',province:'Western Cape',lon:19.4411747,lat:-33.6394993,km:1408,arrival:'Day 2 · 09:45',tagline:'Vineyards under the Hex River mountains',teaser:'The Karoo ends and the Cape winelands begin through a dramatic rail pass.',audioTitle:'Down the Hex River Pass',audioLength:'3 min local story',story:'The descent toward Worcester curls through the Hex River Valley, tunnels, vineyards and mountains.',culture:'Cape wine craft, fynbos and valley communities.',attractions:[{name:'Hex River Pass',kind:'Scenic rail',blurb:'Tunnels and mountain scenery.'},{name:'Breede River Valley',kind:'Winelands',blurb:'Vineyards and cellar experiences.'}],food:['Local wine','Roosterkoek'],image:'/assets/photos/worcester.webp'},
{id:'cape-town',name:'Cape Town',province:'Western Cape',lon:18.4263523,lat:-33.9224221,km:1582,arrival:'Day 2 · 12:10 arrival',tagline:'Under the tablecloth, the line ends at the sea',teaser:'Table Mountain, the Atlantic and the last whistle of the Shosholoza Trail.',audioTitle:'Arrival: the mountain announces itself',audioLength:'4 min local story',story:'The final hour is a slow reveal. Vineyards give way to the Cape Flats, then Table Mountain appears and the train eases into Cape Town Station.',culture:'Cape Malay food, Kaapse Klopse, isiXhosa, Afrikaans and English braided together.',attractions:[{name:'Table Mountain',kind:'Landmark',blurb:'Cableway and sweeping city views.'},{name:'Bo-Kaap',kind:'Neighbourhood',blurb:'Colourful streets and Cape Malay culture.'},{name:'Robben Island',kind:'Heritage',blurb:'Historic island and museum.'}],food:['Bobotie','Gatsby','Snoek braai'],image:'/assets/photos/cape-town.webp'}];
export const TOTAL_KM=1582,TOTAL_HOURS=27;
const MINLON=15.5,MAXLON=33.5,TOP=-21.5,BOTTOM=-35.5, W=1000,H=700;
export const MAP_W=W,MAP_H=H;
export function project(lon:number,lat:number){return{x:(lon-MINLON)/(MAXLON-MINLON)*W,y:(lat-TOP)/(BOTTOM-TOP)*H}}
const outline:[[number,number],...[number,number][]]=[[16.45,-28.58],[17.4,-28.72],[18.4,-28.9],[19.3,-28.92],[19.98,-28.46],[19.98,-24.77],[20.9,-21.95],[23.5,-21.9],[25.9,-24.7],[27.4,-25.3],[28.4,-24.3],[29.4,-22.2],[31.3,-22.35],[32,-25.2],[32.9,-26.85],[31.95,-27.3],[32.6,-28.3],[31,-29.9],[30,-31],[28.9,-32],[27.4,-33],[26,-33.75],[24.8,-34.2],[22.5,-34.05],[20,-34.85],[18.85,-34.35],[18.35,-33],[17.9,-32.8],[17.1,-30.5],[16.45,-28.58]];
export const SA_PATH=outline.map(([lon,lat],i)=>{const p=project(lon,lat);return `${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`}).join(' ')+' Z';
const nodes=[[28.19,-25.75],[28.05,-26.2],[27.5,-26.55],[26.66,-26.87],[25.6,-27.7],[24.77,-28.74],[24.2,-30.1],[24.01,-30.65],[23.5,-31.4],[22.58,-32.36],[21.1,-33.05],[20.58,-33.23],[19.45,-33.65],[18.75,-33.9],[18.42,-33.93]] as [number,number][];
export const ROUTE_POINTS=nodes.map(([a,b])=>project(a,b));
export const ROUTE_PATH=ROUTE_POINTS.map((p,i)=>`${i?'L':'M'}${p.x} ${p.y}`).join(' ');
const stopNode=[0,1,5,7,9,11,12,14];
let cum=[0];for(let i=1;i<ROUTE_POINTS.length;i++){cum.push(cum[i-1]+Math.hypot(ROUTE_POINTS[i].x-ROUTE_POINTS[i-1].x,ROUTE_POINTS[i].y-ROUTE_POINTS[i-1].y))} const total=cum.at(-1)!;
export const STOP_PROGRESS=stopNode.map(i=>cum[i]/total);
export function pointAt(t:number){const target=t*total;let i=1;while(i<cum.length&&cum[i]<target)i++;i=Math.min(i,cum.length-1);const a=ROUTE_POINTS[i-1],b=ROUTE_POINTS[i],span=cum[i]-cum[i-1]||1,f=(target-cum[i-1])/span;return{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f,angle:Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI}}
export function currentStopIndex(t:number){let n=0;STOP_PROGRESS.forEach((p,i)=>{if(t>=p-.004)n=i});return n}
export function nextStopIndex(t:number){const i=STOP_PROGRESS.findIndex(p=>t<p-.004);return i<0?STOPS.length-1:i}
