"""
Seed data for the demonstration database.

The stop names, kilometres, positions and photographs are the SAME ones the app
ships. They used to be a second, independently typed copy, which is how this
file ended up with Cape Town at 1 582 km and stock photographs of the wrong
continent - a Californian canyon standing in for Kimberley, a mountain valley
for Worcester. Kilometres and coordinates now come from app/corridor.py; the
photographs are the verified Wikimedia Commons images of the actual towns.
"""
from . import corridor

_PLACES: dict[str, list[dict]] = {   'pretoria': [   {   'id': 'union',
                        'name': 'Union Buildings',
                        'category': 'Landmark',
                        'type': 'attraction',
                        'distance': '3.8 km',
                        'rating': 4.7,
                        'blurb': 'Terraced gardens and panoramic city views from Meintjieskop.',
                        'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Union%20Buildings%20Pretoria%2003.jpg?width=900',
                        'featured': True},
                    {   'id': 'market',
                        'name': 'Church Square Makers',
                        'category': 'Craft market',
                        'type': 'vendor',
                        'distance': '1.2 km',
                        'rating': 4.6,
                        'price': 'R',
                        'blurb': 'Locally made beadwork, prints and small-batch gifts.',
                        'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Church%20Square%20Pretoria.jpg?width=900'},
                    {   'id': 'freedom',
                        'name': 'Freedom Park',
                        'category': 'Culture',
                        'type': 'attraction',
                        'distance': '4.1 km',
                        'rating': 4.6,
                        'blurb': "A reflective journey through South Africa's history.",
                        'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Freedom%20Park-333.jpg?width=900'}],
    'johannesburg': [   {   'id': 'maboneng',
                            'name': 'Maboneng Precinct',
                            'category': 'Arts district',
                            'type': 'attraction',
                            'distance': '2.4 km',
                            'rating': 4.5,
                            'blurb': 'Street art, galleries, cafés and weekend energy.',
                            'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Maboneng%20Art%20Installation%20Median.jpg?width=900',
                            'featured': True},
                        {   'id': 'rosebank',
                            'name': 'Rosebank Sunday Market',
                            'category': 'Market',
                            'type': 'vendor',
                            'distance': '8.7 km',
                            'rating': 4.6,
                            'price': 'RR',
                            'blurb': 'African crafts, food stalls and rooftop city views.',
                            'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Clothes%20stalls%20at%20the%20Rosebank%20Sunday%20Market%20June%202026.jpg?width=900'},
                        {   'id': 'constitution',
                            'name': 'Constitution Hill',
                            'category': 'Heritage',
                            'type': 'attraction',
                            'distance': '3.1 km',
                            'rating': 4.7,
                            'blurb': 'A living museum telling the story of democracy.',
                            'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Eternal%20Flame%20on%20Constitution%20Hill%20in%20Johannesburg.JPG?width=900'}],
    'kimberley': [   {   'id': 'bighole',
                         'name': 'The Big Hole',
                         'category': 'Heritage',
                         'type': 'attraction',
                         'distance': '1.8 km',
                         'rating': 4.5,
                         'blurb': 'Explore the open-air museum at the heart of diamond history.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Big%20Hole%2C%20Kimberley%2C%20Northern%20Cape%2C%20South%20Africa%20%2820512571296%29.jpg?width=900',
                         'featured': True},
                     {   'id': 'diamondcraft',
                         'name': 'Diamond City Collective',
                         'category': 'Craft studio',
                         'type': 'vendor',
                         'distance': '1.5 km',
                         'rating': 4.8,
                         'price': 'RR',
                         'blurb': 'Northern Cape ceramics, leatherwork and textiles.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/McGregor%20Museum%2C%20Kimberley%2C%20Northern%20Cape%2C%20South%20Africa%20%2820531739632%29.jpg?width=900'}],
    'de-aar': [   {   'id': 'rail',
                      'name': 'Railway Heritage Walk',
                      'category': 'History',
                      'type': 'attraction',
                      'distance': '0.6 km',
                      'rating': 4.3,
                      'blurb': "Follow the town's story through its railway landmarks.",
                      'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Station%20De%20Aar.JPG?width=900',
                      'featured': True},
                  {   'id': 'padstal',
                      'name': 'Karoo Pantry',
                      'category': 'Food',
                      'type': 'vendor',
                      'distance': '1.1 km',
                      'rating': 4.7,
                      'price': 'R',
                      'blurb': 'Fresh roosterkoek, preserves and road-trip favourites.',
                      'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/051.%201980-12.%20De%20Aar%20Station%2C%20platform%201%20-%20SAR..jpg?width=900'}],
    'beaufort': [   {   'id': 'karoo',
                        'name': 'Karoo National Park',
                        'category': 'Nature',
                        'type': 'attraction',
                        'distance': '7.5 km',
                        'rating': 4.7,
                        'blurb': 'Dramatic koppies, wildlife and quiet Karoo landscapes.',
                        'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Karoo%20National%20Park.jpg?width=900',
                        'featured': True},
                    {   'id': 'salt',
                        'name': 'Salt & Stone Deli',
                        'category': 'Local food',
                        'type': 'vendor',
                        'distance': '1.4 km',
                        'rating': 4.8,
                        'price': 'RR',
                        'blurb': 'Karoo lamb, preserves and artisan picnic boxes.',
                        'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Beaufort%20West%20Arts%20%26%20Crafts%20-%20Central%20Karoo%2C%20South%20Africa%20%283918405939%29.jpg?width=900'}],
    'matjies': [   {   'id': 'milner',
                       'name': 'Lord Milner Hotel',
                       'category': 'Heritage',
                       'type': 'attraction',
                       'distance': '0.2 km',
                       'rating': 4.6,
                       'blurb': 'Step into a beautifully preserved Victorian landmark.',
                       'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/9%202%20058%200001-Lord%20Milner-Matjiesfontein-s.jpg?width=900',
                       'featured': True},
                   {   'id': 'pantry',
                       'name': 'The Coffee House',
                       'category': 'Café',
                       'type': 'vendor',
                       'distance': '0.1 km',
                       'rating': 4.5,
                       'price': 'R',
                       'blurb': 'Homemade bakes and coffee beside the platform.',
                       'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Matjiesfontein%20Lord%20Milner%20Hotel%202.JPG?width=900'}],
    'worcester': [   {   'id': 'garden',
                         'name': 'Karoo Desert Garden',
                         'category': 'Nature',
                         'type': 'attraction',
                         'distance': '3.2 km',
                         'rating': 4.6,
                         'blurb': 'Rare succulents and sweeping views over the valley.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Typical%20Robertson%20Karoo%20vegetation%20-%20Worcester.jpg?width=900',
                         'featured': True},
                     {   'id': 'valley',
                         'name': 'Breede Valley Pantry',
                         'category': 'Produce',
                         'type': 'vendor',
                         'distance': '2.1 km',
                         'rating': 4.8,
                         'price': 'RR',
                         'blurb': 'Local fruit, wine, preserves and farm-made goods.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/WorcesterWC-HighStreet.jpg?width=900'}],
    'cape-town': [   {   'id': 'table',
                         'name': 'Table Mountain',
                         'category': 'Nature',
                         'type': 'attraction',
                         'distance': '6.8 km',
                         'rating': 4.9,
                         'blurb': 'Ride the cableway or hike to an unforgettable panorama.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Cape%20Town%20%28ZA%29%2C%20Table%20Mountain%20--%202024%20--%202821.jpg?width=900',
                         'featured': True},
                     {   'id': 'watershed',
                         'name': 'The Watershed',
                         'category': 'Design market',
                         'type': 'vendor',
                         'distance': '2.9 km',
                         'rating': 4.7,
                         'price': 'RR',
                         'blurb': 'Independent South African design under one roof.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Waterfront%20-%20Clocktower%20%28Cape%20Town%29.jpg?width=900'},
                     {   'id': 'bo-kaap',
                         'name': 'Bo-Kaap Walk',
                         'category': 'Culture',
                         'type': 'attraction',
                         'distance': '2.2 km',
                         'rating': 4.7,
                         'blurb': 'Colourful streets, Cape Malay heritage and food stories.',
                         'image': 'https://commons.wikimedia.org/wiki/Special:FilePath/Chiappini%20Street%2C%20Bo-Kaap%20%2801%29.jpg?width=900'}]}

_TEASERS: dict[str, str] = {   'pretoria': 'Jacarandas, monuments and makers in the capital.',
    'johannesburg': 'Gold-rush history meets contemporary city culture.',
    'kimberley': 'Diamond history and wide Northern Cape skies.',
    'de-aar': 'A legendary rail junction beneath the Karoo sky.',
    'beaufort': 'Karoo wilderness, fossils and clear night skies.',
    'matjies': 'A one-street Victorian village frozen in time.',
    'worcester': 'Vineyards and orchards framed by mountains.',
    'cape-town': 'Mountain, ocean and a city alive with creativity.'}

STOPS: list[dict] = [
    {
        **stop,
        "teaser": _TEASERS[stop["id"]],
        "places": _PLACES[stop["id"]],
    }
    for stop in corridor.STOPS
]
