#!/usr/bin/env python3
"""Fetch the real Gautrain alignment from OpenStreetMap and emit a TS module.

Why this is a separate script: Overpass is not reachable from the dev machine,
the browser, or the build agent on the current network (HTTP 403 at the egress
proxy on all three). Run this from any network that can reach Overpass; the
generated file drops straight into the app and the Pretoria - Johannesburg leg
switches from the PRASA main line to the Gautrain alignment.

    python scripts/fetch_gautrain.py > src/gautrain-geometry.ts

Nothing here invents coordinates. If Overpass cannot be reached it exits
non-zero rather than emitting a plausible-looking straight line.
"""
import json
import sys
import urllib.parse
import urllib.request

ENDPOINTS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
]

# Gautrain's north-south spine: Hatfield - Pretoria - Centurion - Midrand -
# Marlboro - Sandton - Rosebank - Park Station. The airport spur (Marlboro -
# Rhodesfield - OR Tambo) is a separate branch and is fetched with it.
QUERY = """
[out:json][timeout:120];
relation["route"="train"]["operator"~"Gautrain",i];
out geom;
"""


def fetch():
    body = urllib.parse.urlencode({"data": QUERY}).encode()
    last = None
    for endpoint in ENDPOINTS:
        try:
            request = urllib.request.Request(
                endpoint, data=body, headers={"User-Agent": "ShosholozaTrail/1.0"}
            )
            with urllib.request.urlopen(request, timeout=150) as response:
                return json.load(response)
        except Exception as error:  # noqa: BLE001 - report and try the next mirror
            last = error
            print(f"  {endpoint}: {error}", file=sys.stderr)
    raise SystemExit(f"All Overpass mirrors failed; last error: {last}")


def main():
    payload = fetch()
    routes = []
    for element in payload.get("elements", []):
        if element.get("type") != "relation":
            continue
        name = element.get("tags", {}).get("name", "Gautrain")
        coords = []
        for member in element.get("members", []):
            for node in member.get("geometry") or []:
                point = [round(node["lat"], 6), round(node["lon"], 6)]
                if not coords or coords[-1] != point:
                    coords.append(point)
        if len(coords) > 1:
            routes.append({"name": name, "coordinates": coords})

    if not routes:
        raise SystemExit("Overpass returned no Gautrain relations; check the query.")

    print("// Generated by scripts/fetch_gautrain.py. Do not hand edit.")
    print("// Source: OpenStreetMap contributors, ODbL 1.0.")
    print("export interface GautrainRoute { name: string; coordinates: [number, number][]; }")
    print(f"export const gautrainRoutes: GautrainRoute[] = {json.dumps(routes)};")
    print(
        "export const gautrainSpine = gautrainRoutes"
        ".slice().sort((a, b) => b.coordinates.length - a.coordinates.length)[0];"
    )
    for route in routes:
        print(f"// {route['name']}: {len(route['coordinates'])} vertices", file=sys.stderr)


if __name__ == "__main__":
    main()
