/**
 * Turn the data the app already ships into seed SQL.
 *
 * The stops, the published timetable and the OpenStreetMap places are already
 * correct and already reviewed; retyping them into the database by hand would
 * only be a chance to get them wrong. This reads the same modules the app
 * reads and writes an idempotent seed file, so re-running it after the data
 * files change updates the database rather than duplicating it.
 *
 *   npx esbuild scripts/seed-sql.ts --bundle --platform=node --format=cjs \
 *     --outfile=scripts/.seed.cjs && node scripts/.seed.cjs > supabase/seed.sql
 */
import { stops } from "../src/data";
import { NEARBY } from "../src/data/nearby";
import type { Place } from "../src/types";
import { CALL_DAYS, CALLS, DEFAULT_STOP_MINUTES } from "../src/lib/timetable";

const q = (v: string | null | undefined) =>
  v === null || v === undefined || v === "" ? "null" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) =>
  v === null || v === undefined || Number.isNaN(v) ? "null" : String(Math.round(v * 1e6) / 1e6);

const out: string[] = [];
out.push(`-- Generated by scripts/seed-sql.ts. Do not edit by hand.`);
out.push(`-- Re-running this is safe: every statement is an upsert.`);
out.push(``);

out.push(`insert into services (id, name, direction) values`);
out.push(`  ('meyl-pta-cpt', 'Shosholoza Meyl — Pretoria to Cape Town', 'southbound')`);
out.push(`on conflict (id) do update set name = excluded.name, direction = excluded.direction;`);
out.push(``);

out.push(`insert into stops (id, name, km, lat, lon) values`);
out.push(
  stops
    .map(s => `  (${q(s.id)}, ${q(s.name)}, ${n(s.km)}, ${n(s.lat)}, ${n(s.lon)})`)
    .join(",\n"),
);
out.push(`on conflict (id) do update set`);
out.push(`  name = excluded.name, km = excluded.km, lat = excluded.lat, lon = excluded.lon;`);
out.push(``);

// The published calls, in order. Calls at places that are not modelled stops
// (Klerksdorp, Wellington, Bellville) are skipped rather than invented.
const known = new Set(stops.map(s => s.id));
// CALL_DAYS carries the overnight rollover - Beaufort West at 03:40 is the
// morning AFTER an 08:30 departure from Pretoria, not four hours before it.
// Reading c.day here instead (a field Call does not have) quietly flattened
// every call onto day one, which a consistency test caught.
const rows = CALLS
  .map((c, i) => ({ c, day: CALL_DAYS[i] }))
  .filter(({ c }) => c.stopId && known.has(c.stopId));
out.push(`insert into calls (service_id, stop_id, seq, sched_time, day_offset, dwell_minutes) values`);
out.push(
  rows
    .map(({ c, day }, seq) =>
      `  ('meyl-pta-cpt', ${q(c.stopId!)}, ${seq + 1}, ${q(c.time + ":00")}, ${day - 1}, ${DEFAULT_STOP_MINUTES})`,
    )
    .join(",\n"),
);
out.push(`on conflict (service_id, seq) do update set`);
out.push(`  stop_id = excluded.stop_id, sched_time = excluded.sched_time,`);
out.push(`  day_offset = excluded.day_offset, dwell_minutes = excluded.dwell_minutes;`);
out.push(``);

const slugify = (s: string) =>
  s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const placeRows: string[] = [];
const seen = new Set<string>();
const push = (
  slug: string, stopId: string, name: string, kind: string,
  lat: number | undefined, lon: number | undefined,
  dist: number | undefined, cuisine: string | undefined, source: "osm" | "claimed",
) => {
  if (seen.has(slug)) return;
  seen.add(slug);
  placeRows.push(
    `  (${q(slug)}, ${q(stopId)}, ${q(name)}, ${q(kind)}, ${n(lat)}, ${n(lon)}, ${n(dist)}, ${q(cuisine)}, ${q(source)})`,
  );
};

// The editorial cards first — these are the ones that carry a Reserve button,
// so the app must be able to name them.
for (const stop of stops) {
  for (const place of stop.places as Place[]) {
    const km = Number.parseFloat(place.distance);
    push(`ed:${place.id}`, stop.id, place.name, place.type, undefined, undefined,
         Number.isFinite(km) ? km : undefined, undefined, "osm");
  }
}

for (const [stopId, list] of Object.entries(NEARBY)) {
  if (!known.has(stopId)) continue;
  for (const p of list) {
    push(`osm:${stopId}:${slugify(p.n)}`, stopId, p.n, p.k, p.la, p.lo, p.d, p.c, "osm");
  }
}

out.push(`-- source = 'osm' means no one at these businesses has agreed to anything,`);
out.push(`-- and the app must keep saying so until a verified merchant claims the row.`);
out.push(`insert into places (slug, stop_id, name, kind, lat, lon, distance_km, cuisine, source) values`);
out.push(placeRows.join(",\n"));
out.push(`on conflict (slug) do update set`);
out.push(`  stop_id = excluded.stop_id, name = excluded.name, kind = excluded.kind,`);
out.push(`  lat = excluded.lat, lon = excluded.lon,`);
out.push(`  distance_km = excluded.distance_km, cuisine = excluded.cuisine;`);
out.push(``);

process.stdout.write(out.join("\n") + "\n");
